
--1) addres tablosunun kontrol etmek için top 100 ünü çekiniz.

SELECT TOP 100 * FROM ADDRESS

--2)CITIES tablosuna yeni bir kayýt olarak ID,COUNTRYID VE memlektenizi ekleyin.

SELECT * FROM CITIES

INSERT INTO CITIES
(ID, COUNTRYID, CITY)
VALUES
(82, 1, 'NÝÐDE')

--3)[dbo].[USERS] tablosundaki 10 numaralý id yi kendi bilgileriniz ile update edin.

SELECT * FROM [dbo].[USERS]

UPDATE [dbo].[USERS]
SET USERNAME_ = 'E_EROGLU'
,PASSWORD_ = 'eda123'
,NAMESURNAME = 'Eda EROÐLU'
,EMAIL = 'E_EROGLU@sqlegitimbtk.com'
,GENDER = 'K'
,BIRTHDATE = '2000-03-04'
,CREATEDDATE = GETDATE() 
,TELNR1 = '(539)5395390'
,TELNR2 = '(539)5395391'
WHERE ID = 10

SELECT * FROM [dbo].[USERS] WHERE ID = 10

--4)[dbo].[SALEORDERS] tablosunda category1 i SEKERLEME OLAN KAYITLARI GETÝRÝN.

SELECT * FROM [dbo].[SALEORDERS] WHERE CATEGORY1 = 'SEKERLEME'

--5)[dbo].[SALEORDERS] tablosunda LINETOTALI 20.000 DEN BUYUK KAYITLARI GETIRIN.

SELECT * FROM [dbo].[SALEORDERS] WHERE LINETOTAL > 20.000

--6)[dbo].[SALEORDERS] tablosunda haftaiçi olan kayýtlarý getirin.

SELECT * FROM [dbo].[SALEORDERS] WHERE DAYOFWEEK_ <> 'Cumartesi' AND DAYOFWEEK_ <> 'Pazar' --Cumartesi ve Pazar olmayanlarý getirir

--7)[dbo].[SALEORDERS] tablosunda pazar günü ve Tablet satýþlarýný getirin.

SELECT * FROM [dbo].[SALEORDERS] WHERE DAYOFWEEK_ = 'Pazar' AND CATEGORY4 = 'Tablet'

--8)[dbo].[ITEMS]tablosunda kaç tane tekin category1 vardýr.

SELECT DISTINCT CATEGORY1 FROM [dbo].[ITEMS]

--9)[dbo].[ITEMS]tablosundaki ürünleri unitprice a göre büyükten küçüðe sýralayýnýz.

SELECT * FROM [dbo].[ITEMS]
ORDER BY UNITPRICE DESC

--10)[dbo].[SALEORDERS] tablosunda þehirlere göre (SUM,COUNT,MIN,MAX,AVG) adeti getirin.

SELECT * FROM [dbo].[SALEORDERS]

SELECT CITY,SUM(AMOUNT)SUM,
COUNT(AMOUNT)COUNT,
MIN(AMOUNT)MIN,
MAX(AMOUNT)MAX,
AVG(AMOUNT)AVG
FROM [dbo].[SALEORDERS] 
GROUP BY CITY ORDER BY CITY

--11) ÜRÜN KATEGORÝLERÝNE GÖRE TOPLAM SATIÞLARý getirin.

SELECT CATEGORY1,CATEGORY2, CATEGORY3, CATEGORY4,
SUM(AMOUNT)AMOUNT
FROM [dbo].[SALEORDERS]
GROUP BY CATEGORY1,CATEGORY2, CATEGORY3, CATEGORY4 ORDER BY AMOUNT

--12)order ve user tablolarýný left,right ve inner olarak þekilde birleþtiriniz.

SELECT * FROM [dbo].[ORDERS]
INNER JOIN [dbo].[USERS] ON ORDERS.USERID = USERS.ID

SELECT * FROM [dbo].[ORDERS]
LEFT JOIN [dbo].[USERS] ON ORDERS.USERID = USERS.ID

SELECT * FROM [dbo].[USERS]
RIGHT JOIN [dbo].[ORDERS] ON ORDERS.USERID = USERS.ID

--13)adress ve user tablolarýný left,right ve inner olarak þekilde birleþtiriniz.

SELECT * FROM [dbo].[ADDRESS]
INNER JOIN [dbo].[USERS] ON ADDRESS.USERID = USERS.ID

SELECT * FROM [dbo].[ADDRESS]
LEFT JOIN [dbo].[USERS] ON ADDRESS.USERID = USERS.ID

SELECT * FROM [dbo].[USERS]
RIGHT JOIN [dbo].[ADDRESS] ON ADDRESS.USERID = USERS.ID

--14)En fazla alýþveriþ hangi markada yapýlmýþtýr.

SELECT SUM(AMOUNT), BRAND FROM [dbo].[ORDERS]
INNER JOIN ORDERDETAILS ON ORDERS.ID = ORDERDETAILS.ORDERID
INNER JOIN ITEMS ON ITEMS.ID = ORDERDETAILS.ITEMID
GROUP BY BRAND

--15)oyuncak ANA KATEGORÝSÝNDE KATEGORÝSÝNDE, ZEKA GELISTIRICI UST KATEGORISINDE, OYUNCAKLAR ALT KATEGORISINDE EN FAZLA SATIÞ YAPAN, bebe oyuncaklarý nelerdir?

SELECT ITEMNAME, SUM(AMOUNT) AS SATIS FROM [dbo].[ORDERS]
INNER JOIN ORDERDETAILS ON ORDERS.ID = ORDERDETAILS.ORDERID
INNER JOIN ITEMS ON ITEMS.ID = ORDERDETAILS.ITEMID
WHERE CATEGORY1 = 'OYUNCAK' AND CATEGORY2 = 'ZEKA GELISTIRICI' AND CATEGORY3 = 'OYUNCAKLAR' AND CATEGORY4 = 'BEBE OYUNCAK'
GROUP BY ITEMNAME
ORDER BY SATIS DESC

--16) TEMIZLIK KATEGORÝSÝNDEKI URUNLERIN ORTALAMA FÝYAT NEDÝR

SELECT ITEMNAME, AVG(TOTALPRICE) FROM [dbo].[ORDERS]
INNER JOIN ORDERDETAILS ON ORDERS.ID = ORDERDETAILS.ORDERID
INNER JOIN ITEMS ON ITEMS.ID = ORDERDETAILS.ITEMID
WHERE CATEGORY1 = 'TEMIZLIK'
GROUP BY ITEMNAME

--17) HANGÝ YAÞ GRUPLARI DAHA FAZLA ALIÞVERÝÞ YAPMIÞtýr

--18)[dbo].[ITEMS] TABLOSUNDAKÝ TÜM CATERGORYLERÝ BÝRLEÞTÝRÝN.

SELECT *, CONCAT (CATEGORY1, ',',  CATEGORY2, ',', CATEGORY3, ',', CATEGORY4) AS CATEGORIES FROM [dbo].[ITEMS]

--19)[dbo].[PAYMENTS] TABLOSUNDAKÝ APPROVECODE KOLONUNUN ILK 5 DEÐERÝNÝ AYRI BÝR KOLON OLARAK YAZIN.

SELECT LEFT(APPROVECODE,5) FROM [dbo].[PAYMENTS]

--20)[dbo].[PAYMENTS] TABLOSUNDAKÝ SAYISAL DEÐERLERÝ AYRI BÝR KOLON OLARAK YAZIN.

SELECT RIGHT (APPROVECODE, 9 ) FROM [dbo].[PAYMENTS]

--21)[dbo].[USERS] TABLOSUNDAKÝ PASSWORD KOLONUNU TÜM DEÐERLERÝ BÜYÜK YAZIN.

SELECT UPPER(PASSWORD_) PASSWORD FROM [dbo].[USERS] 

--22)[dbo].[USERS] TABLOSUNDAKÝ NAMESURNAME  KOLONUNUNDAKÝ SOYÝSÝMLERÝ TÜM DEÐERLERÝ KÜÇÜK YAZIN.

SELECT CONCAT(
LEFT (NAMESURNAME, CHARINDEX(' ', NAMESURNAME)),
LOWER(SUBSTRING(NAMESURNAME, CHARINDEX(' ', NAMESURNAME) + 1, LEN(NAMESURNAME)))
) FROM [dbo].[USERS]

--23)[dbo].[INVOICES] TABLOSUNDAKÝ DATE KOLONUNU AÞAÐIDAKÝ FORMATLARA ÇEVÝRÝN.
			--mm/dd/yyyy
			--yyyy.mm.dd
			--dd.mm.yyyy
			--yyyymmdd

SELECT 
FORMAT(DATE_, 'MM/dd/yyyy') mm_dd_yyyy,
FORMAT(DATE_, 'yyyy.MM.dd') yyyy_mm_dd,
FORMAT(DATE_, 'dd.MM.yyyy') dd_mm_yyyy,
CONVERT(varchar(8), DATE_, 112) yyyymmdd
FROM [dbo].[INVOICES]

--24)[dbo].[INVOICES] TABLOSUNDAKÝ DATE KOLONUNU YIL,AY,GUN,HAFTA OLARAK AYRI AYIR KOLONLARDA GÖSTERÝN.

SELECT DATEPART(YEAR, DATE_) YIL, DATEPART(MONTH, DATE_) AY, DATEPART(DAY, DATE_) GÜN FROM [dbo].[INVOICES]

--25)[dbo].[SALEORDERS] TABLOSUNDAKÝ MONTH KOLONUNA GÖRE HANGÝ AYIN HANGÝ MEVSÝME GELDÝÐÝNÝ YAZIN.

SELECT 
CASE
	WHEN MONTH_ IN('Mart', 'Nisan', 'Mayýs') THEN 'Ýlkbahar'
	WHEN MONTH_ IN('Haziran', 'Temmuz', 'Aðustos') THEN 'Yaz'
	WHEN MONTH_ IN('Eylül', 'Ekim', 'Kasým') THEN 'Sonbahar'
	WHEN MONTH_ IN('Aralýk', 'Ocak', 'Þubat') THEN 'Kýþ'
	ELSE 'NULL'
END MEVSIMLER FROM [dbo].[SALEORDERS]

--26)[dbo].[ITEMS] TABLOSUDNAKÝ BRANLERÝ AÞAÐIDAKÝ KURALA GÖRE YENÝ BÝR KOLON OLUÞTURUNUZ.
		--ULKER ISE YEME ICME
		--REXONA ISE KOZMATIK
		--ALGIDA ISE DONDURMA
		--NESCAFE ISE SICAKICECEK
		--BUNLARIN DIÞINDAKILER DIGER 

SELECT DISTINCT(BRAND),
CASE 
	WHEN BRAND = 'ULKER' THEN 'YEME-ICME'
	WHEN BRAND = 'REXONA' THEN 'KOZMETIK'
	WHEN BRAND = 'ALGIDA' THEN 'DONDURMA'
	WHEN BRAND = 'NESCAFE' THEN 'SICAK ICECEK'
	ELSE 'DIGER' 
END CATEGORY FROM [dbo].[ITEMS]